# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mialikescoffee.com
email: mail@mialikescoffee.com
description: >- # this means to ignore newlines until "baseurl:"
  Ein Blog über IT, Security und Privacy. Powered by coffee.
twitter_username: jln0x1
minimal_mistakes_skin: contrast
search: true
show_date: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin
locale: de_DE
logo: "/images/logo_terminal.png"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Julian"
  avatar : "/assets/images/biopic.png"
  bio    : "Willkommen auf meinem Blog. Hier schreibe ich über Security, Privacy, CTFs (capture the flag) und andere IT-Themen."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mialikescoffee.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jln0x1"
    - label: "Mastodon"
      icon: "fab fa-mastodon"
      url: "https://social.tchncs.de/web/@mialikescoffee"
    
    
  
   

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jln0x1"
    - label: "Email"
      icon: "fas fa-at"
      url: "mailto:mail@mialikescoffee.com"
      
      
   

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
